language: generic 
sudo: required
services:
  - docker

# testing first
before_install:
  - docker build -t gregoriusjimmy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gregoriusjimmy/react-test npm test

after_success:
  - docker build -t gregoriusjimmy/multi-client ./client
  - docker build -t gregoriusjimmy/multi-nginx ./nginx
  - docker build -t gregoriusjimmy/multi-server ./server
  - docker build -t gregoriusjimmy/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gregoriusjimmy/multi-client
  - docker push gregoriusjimmy/multi-nginx
  - docker push gregoriusjimmy/multi-server
  - docker push gregoriusjimmy/multi-worker